esphome:
  name: fujitsu-firebeetle

esp32:
  board: dfrobot_firebeetle2_esp32e
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components
    components: [fujitsu]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "FujitsuFireBeetle"
    password: !secret ap_password

captive_portal:

climate:
  - platform: fujitsu
    name: "Fujitsu"
    tx_pin: 1    # IO1 / D1 / TXD
    rx_pin: 3    # IO3 / D0 / RXD
    en_pin: 25
    nrst_pin: 26
