esphome:
  name: fujitsu

esp32:
  board: dfrobot_firebeetle2_esp32e
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components
    components: [fujitsu]

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ssid: "your wifi ssid"
  password: "your password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fujitsu"
    password: "a password for captive portal"

captive_portal:

climate:
  - platform: fujitsu
    name: "Fujitsu"
    rx_pin: 16
    tx_pin: 17
    en_pin: 25
    nrst_pin: 26
